import { DnsServer, RuleType, RuleAction, DomainStrategy, ClashMode } from '@/enums'
import { sampleID } from '@/utils'

import { DefaultDnsServersIds, DefaultOutboundIds, DefaultRulesetIds } from '../shared'

export const DefaultDnsServer = (): App.DnsServerConfig => ({
  id: sampleID(),
  tag: '',
  type: DnsServer.Local,
  detour: '',
  domain_resolver: '',
  server: '',
  server_port: '',
  path: '',
  interface: '',
  inet4_range: '',
  inet6_range: '',
  hosts_path: [],
  predefined: {},
})

export const DefaultDnsServers = (): App.DnsServerConfig[] => [
  {
    id: DefaultDnsServersIds.FakeIP,
    tag: DefaultDnsServersIds.FakeIP,
    detour: '',
    type: DnsServer.FakeIp,
    domain_resolver: '',
    server: '',
    server_port: '',
    path: '',
    interface: '',
    inet4_range: '198.18.0.0/15',
    inet6_range: 'fc00::/18',
    hosts_path: [],
    predefined: {},
  },
  {
    id: DefaultDnsServersIds.LocalDns,
    tag: DefaultDnsServersIds.LocalDns,
    detour: '',
    type: DnsServer.Https,
    domain_resolver: DefaultDnsServersIds.LocalDnsResolver,
    server: '223.5.5.5',
    server_port: '443',
    path: '/dns-query',
    interface: '',
    inet4_range: '',
    inet6_range: '',
    hosts_path: [],
    predefined: {},
  },
  {
    id: DefaultDnsServersIds.LocalDnsResolver,
    tag: DefaultDnsServersIds.LocalDnsResolver,
    detour: '',
    type: DnsServer.Udp,
    domain_resolver: '',
    server: '223.5.5.5',
    server_port: '53',
    path: '',
    interface: '',
    inet4_range: '',
    inet6_range: '',
    hosts_path: [],
    predefined: {},
  },
  {
    id: DefaultDnsServersIds.RemoteDns,
    tag: DefaultDnsServersIds.RemoteDns,
    detour: DefaultOutboundIds.Select,
    type: DnsServer.Tls,
    domain_resolver: DefaultDnsServersIds.RemoteDnsResolver,
    server: '8.8.8.8',
    server_port: '853',
    path: '',
    interface: '',
    inet4_range: '',
    inet6_range: '',
    hosts_path: [],
    predefined: {},
  },
  {
    id: DefaultDnsServersIds.RemoteDnsResolver,
    tag: DefaultDnsServersIds.RemoteDnsResolver,
    detour: DefaultOutboundIds.Select,
    type: DnsServer.Udp,
    domain_resolver: '',
    server: '8.8.8.8',
    server_port: '53',
    path: '',
    interface: '',
    inet4_range: '',
    inet6_range: '',
    hosts_path: [],
    predefined: {},
  },
]

export const DefaultFakeIPDnsRule = () => ({
  __is_fake_ip: true,
  type: 'logical',
  mode: 'and',
  rules: [
    {
      domain_suffix: [
        '.lan',
        '.localdomain',
        '.example',
        '.invalid',
        '.localhost',
        '.test',
        '.local',
        '.home.arpa',
        '.msftconnecttest.com',
        '.msftncsi.com',
      ],
      invert: true,
    },
    {
      query_type: ['A', 'AAAA'],
    },
  ],
})

export const DefaultDnsRule = (): App.DnsRule => ({
  id: sampleID(),
  type: RuleType.RuleSet,
  enable: true,
  payload: '',
  action: RuleAction.Route,
  invert: false,
  // route
  server: '',
  strategy: DomainStrategy.Default,
  // route/route-options
  disable_cache: false,
  client_subnet: '',
})

export const DefaultDnsRules = (): App.DnsRule[] => [
  {
    id: sampleID(),
    type: RuleType.ClashMode,
    enable: true,
    payload: ClashMode.Direct,
    action: RuleAction.Route,
    server: DefaultDnsServersIds.LocalDns,
    invert: false,
    strategy: DomainStrategy.Default,
    disable_cache: false,
    client_subnet: '',
  },
  {
    id: sampleID(),
    type: RuleType.ClashMode,
    enable: true,
    payload: ClashMode.Global,
    action: RuleAction.Route,
    server: DefaultDnsServersIds.RemoteDns,
    invert: false,
    strategy: DomainStrategy.Default,
    disable_cache: false,
    client_subnet: '',
  },
  {
    id: RuleType.InsertionPoint,
    type: RuleType.InsertionPoint,
    enable: true,
    payload: '',
    action: RuleAction.Route,
    server: '',
    invert: false,
    strategy: DomainStrategy.Default,
    disable_cache: false,
    client_subnet: '',
  },
  {
    id: sampleID(),
    type: RuleType.RuleSet,
    enable: true,
    payload: DefaultRulesetIds.GEOSITE_CN,
    action: RuleAction.Route,
    server: DefaultDnsServersIds.LocalDns,
    invert: false,
    strategy: DomainStrategy.Default,
    disable_cache: false,
    client_subnet: '',
  },
  {
    id: sampleID(),
    type: RuleType.Inline,
    enable: false,
    payload: JSON.stringify(DefaultFakeIPDnsRule(), null, 2),
    action: RuleAction.Route,
    server: DefaultDnsServersIds.FakeIP,
    invert: false,
    strategy: DomainStrategy.Default,
    disable_cache: false,
    client_subnet: '',
  },
  {
    id: sampleID(),
    type: RuleType.RuleSet,
    enable: true,
    payload: DefaultRulesetIds.GEOLOCATION_NOT_CN,
    action: RuleAction.Route,
    server: DefaultDnsServersIds.RemoteDns,
    invert: false,
    strategy: DomainStrategy.Default,
    disable_cache: false,
    client_subnet: '',
  },
]

export const DefaultDns = (): App.Dns => ({
  servers: DefaultDnsServers(),
  rules: DefaultDnsRules(),
  disable_cache: false,
  disable_expire: false,
  independent_cache: false,
  client_subnet: '',
  final: DefaultDnsServersIds.RemoteDns,
  strategy: DomainStrategy.Default,
})
