import {
  RuleType,
  RuleAction,
  DomainStrategy,
  RuleSetType,
  RuleSetFormat,
  ClashMode,
} from '@/enums'
import { sampleID } from '@/utils'

import {
  DefaultInboundIds,
  DefaultOutboundIds,
  DefaultRulesetIds,
  DefaultDnsServersIds,
} from '../shared'

export const DefaultRouteRule = (): App.Rule => ({
  id: sampleID(),
  type: RuleType.RuleSet,
  enable: true,
  payload: '',
  invert: false,
  action: RuleAction.Route,
  outbound: '',
  sniffer: [],
  strategy: DomainStrategy.Default,
  server: '',
})

export const DefaultRouteRuleset = (): App.ProfileRuleSet => ({
  id: sampleID(),
  type: RuleSetType.Local,
  tag: '',
  format: RuleSetFormat.Binary,
  url: '',
  download_detour: '',
  update_interval: '',
  rules: '',
  path: '',
})

export const DefaultRoute = (): App.Route => ({
  rules: [
    {
      id: sampleID(),
      type: RuleType.Inbound,
      payload: DefaultInboundIds.Tun,
      enable: true,
      invert: false,
      action: RuleAction.Sniff,
      outbound: '',
      sniffer: [],
      strategy: DomainStrategy.Default,
      server: '',
    },
    {
      id: sampleID(),
      type: RuleType.Protocol,
      enable: true,
      payload: 'dns',
      invert: false,
      action: RuleAction.HijackDns,
      outbound: '',
      sniffer: [],
      strategy: DomainStrategy.Default,
      server: '',
    },
    {
      id: sampleID(),
      type: RuleType.ClashMode,
      payload: ClashMode.Direct,
      enable: true,
      invert: false,
      action: RuleAction.Route,
      outbound: DefaultOutboundIds.Direct,
      sniffer: [],
      strategy: DomainStrategy.Default,
      server: '',
    },
    {
      id: sampleID(),
      type: RuleType.ClashMode,
      enable: true,
      payload: ClashMode.Global,
      invert: false,
      action: RuleAction.Route,
      outbound: DefaultOutboundIds.Global,
      sniffer: [],
      strategy: DomainStrategy.Default,
      server: '',
    },
    {
      id: RuleType.InsertionPoint,
      type: RuleType.InsertionPoint,
      enable: true,
      payload: '',
      invert: false,
      action: RuleAction.Route,
      outbound: '',
      sniffer: [],
      strategy: DomainStrategy.Default,
      server: '',
    },
    {
      id: sampleID(),
      type: RuleType.Network,
      enable: true,
      payload: 'icmp',
      invert: false,
      action: RuleAction.Route,
      outbound: DefaultOutboundIds.Direct,
      sniffer: [],
      strategy: DomainStrategy.Default,
      server: '',
    },
    {
      id: sampleID(),
      type: RuleType.Protocol,
      enable: true,
      payload: 'quic',
      invert: false,
      action: RuleAction.Route,
      outbound: DefaultOutboundIds.Block,
      sniffer: [],
      strategy: DomainStrategy.Default,
      server: '',
    },
    {
      id: sampleID(),
      type: RuleType.RuleSet,
      enable: true,
      payload: DefaultRulesetIds.CATEGORY_ADS,
      invert: false,
      action: RuleAction.Route,
      outbound: DefaultOutboundIds.Block,
      sniffer: [],
      strategy: DomainStrategy.Default,
      server: '',
    },
    {
      id: sampleID(),
      type: RuleType.RuleSet,
      enable: true,
      payload: DefaultRulesetIds.GEOSITE_PRIVATE,
      invert: false,
      action: RuleAction.Route,
      outbound: DefaultOutboundIds.Direct,
      sniffer: [],
      strategy: DomainStrategy.Default,
      server: '',
    },
    {
      id: sampleID(),
      type: RuleType.RuleSet,
      enable: true,
      payload: DefaultRulesetIds.GEOSITE_CN,
      invert: false,
      action: RuleAction.Route,
      outbound: DefaultOutboundIds.Direct,
      sniffer: [],
      strategy: DomainStrategy.Default,
      server: '',
    },
    {
      id: sampleID(),
      type: RuleType.RuleSet,
      enable: true,
      payload: DefaultRulesetIds.GEOIP_PRIVATE,
      invert: false,
      action: RuleAction.Route,
      outbound: DefaultOutboundIds.Direct,
      sniffer: [],
      strategy: DomainStrategy.Default,
      server: '',
    },
    {
      id: sampleID(),
      type: RuleType.RuleSet,
      enable: true,
      payload: DefaultRulesetIds.GEOIP_CN,
      invert: false,
      action: RuleAction.Route,
      outbound: DefaultOutboundIds.Direct,
      sniffer: [],
      strategy: DomainStrategy.Default,
      server: '',
    },
    {
      id: sampleID(),
      type: RuleType.RuleSet,
      enable: true,
      payload: DefaultRulesetIds.GEOLOCATION_NOT_CN,
      invert: false,
      action: RuleAction.Route,
      outbound: DefaultOutboundIds.Select,
      sniffer: [],
      strategy: DomainStrategy.Default,
      server: '',
    },
  ],
  rule_set: [
    {
      id: DefaultRulesetIds.CATEGORY_ADS,
      type: RuleSetType.Remote,
      tag: DefaultRulesetIds.CATEGORY_ADS,
      format: RuleSetFormat.Binary,
      url: 'https://testingcf.jsdelivr.net/gh/MetaCubeX/meta-rules-dat@sing/geo/geosite/category-ads-all.srs',
      download_detour: DefaultOutboundIds.Direct,
      update_interval: '',
      rules: '',
      path: '',
    },
    {
      id: DefaultRulesetIds.GEOIP_PRIVATE,
      type: RuleSetType.Remote,
      tag: DefaultRulesetIds.GEOIP_PRIVATE,
      format: RuleSetFormat.Binary,
      url: 'https://testingcf.jsdelivr.net/gh/MetaCubeX/meta-rules-dat@sing/geo/geoip/private.srs',
      download_detour: DefaultOutboundIds.Direct,
      update_interval: '',
      rules: '',
      path: '',
    },
    {
      id: DefaultRulesetIds.GEOSITE_PRIVATE,
      type: RuleSetType.Remote,
      tag: DefaultRulesetIds.GEOSITE_PRIVATE,
      format: RuleSetFormat.Binary,
      url: 'https://testingcf.jsdelivr.net/gh/MetaCubeX/meta-rules-dat@sing/geo/geosite/private.srs',
      download_detour: DefaultOutboundIds.Direct,
      update_interval: '',
      rules: '',
      path: '',
    },
    {
      id: DefaultRulesetIds.GEOIP_CN,
      type: RuleSetType.Remote,
      tag: DefaultRulesetIds.GEOIP_CN,
      format: RuleSetFormat.Binary,
      url: 'https://testingcf.jsdelivr.net/gh/MetaCubeX/meta-rules-dat@sing/geo/geoip/cn.srs',
      download_detour: DefaultOutboundIds.Direct,
      update_interval: '',
      rules: '',
      path: '',
    },
    {
      id: DefaultRulesetIds.GEOSITE_CN,
      type: RuleSetType.Remote,
      tag: DefaultRulesetIds.GEOSITE_CN,
      format: RuleSetFormat.Binary,
      url: 'https://testingcf.jsdelivr.net/gh/MetaCubeX/meta-rules-dat@sing/geo/geosite/cn.srs',
      download_detour: DefaultOutboundIds.Direct,
      update_interval: '',
      rules: '',
      path: '',
    },
    {
      id: DefaultRulesetIds.GEOLOCATION_NOT_CN,
      type: RuleSetType.Remote,
      tag: DefaultRulesetIds.GEOLOCATION_NOT_CN,
      format: RuleSetFormat.Binary,
      url: 'https://testingcf.jsdelivr.net/gh/MetaCubeX/meta-rules-dat@sing/geo/geosite/geolocation-!cn.srs',
      download_detour: DefaultOutboundIds.Direct,
      update_interval: '',
      rules: '',
      path: '',
    },
  ],
  auto_detect_interface: true,
  default_interface: '',
  final: DefaultOutboundIds.Fallback,
  find_process: false,
  default_domain_resolver: {
    server: DefaultDnsServersIds.LocalDns,
    client_subnet: '',
  },
})
