import { generateConfig } from '@generator'
import type { Profile } from '@profiles'

import { WriteFile } from '@/bridge/io'

import { CoreConfigFilePath } from '@/constant/kernel'

import type { Recordable } from '@/types/typescript'

import { APP_TITLE } from './env'

export const generateConfigFile = async (
  profile: Profile,
  beforeWrite: (config: Recordable) => Promise<Recordable>,
) => {
  const header = `DO NOT EDIT - Auto Generated by ${APP_TITLE}`

  const config = await generateConfig(profile)
  const finalConfig = await beforeWrite(config)

  await WriteFile(CoreConfigFilePath, JSON.stringify({ $schema: header, ...finalConfig }, null, 2))
}
