import type { DomainStrategy } from '@profile/constant/kernel'
import { DnsRuleType, ClashMode, DnsServerType, DnsActionKind } from '@profile/constant/kernel'
import type { DnsRuleItem, DnsSection, DnsServerItem } from '@profile/types/profiles/dns'

import { sampleID } from '@/utils/others'

import { DefaultDnsServersIds, DefaultOutboundIds, DefaultRulesetIds } from './shared'

export const createDnsServer = (): DnsServerItem => ({
  id: sampleID(),
  tag: '',
  type: DnsServerType.Local,
  detour: '',
  domain_resolver: '',
  server: '',
  server_port: '',
  path: '',
  interface: '',
  inet4_range: '',
  inet6_range: '',
  hosts_path: [],
  predefined: {},
})

export const createDnsServers = (): DnsServerItem[] => [
  {
    id: DefaultDnsServersIds.FakeIP,
    tag: DefaultDnsServersIds.FakeIP,
    detour: '',
    type: DnsServerType.FakeIp,
    domain_resolver: '',
    server: '',
    server_port: '',
    path: '',
    interface: '',
    inet4_range: '198.18.0.0/15',
    inet6_range: 'fc00::/18',
    hosts_path: [],
    predefined: {},
  },
  {
    id: DefaultDnsServersIds.LocalDns,
    tag: DefaultDnsServersIds.LocalDns,
    detour: '',
    type: DnsServerType.Https,
    domain_resolver: DefaultDnsServersIds.LocalDnsResolver,
    server: '223.5.5.5',
    server_port: '443',
    path: '/dns-query',
    interface: '',
    inet4_range: '',
    inet6_range: '',
    hosts_path: [],
    predefined: {},
  },
  {
    id: DefaultDnsServersIds.LocalDnsResolver,
    tag: DefaultDnsServersIds.LocalDnsResolver,
    detour: '',
    type: DnsServerType.Udp,
    domain_resolver: '',
    server: '223.5.5.5',
    server_port: '53',
    path: '',
    interface: '',
    inet4_range: '',
    inet6_range: '',
    hosts_path: [],
    predefined: {},
  },
  {
    id: DefaultDnsServersIds.RemoteDns,
    tag: DefaultDnsServersIds.RemoteDns,
    detour: DefaultOutboundIds.Select,
    type: DnsServerType.Tls,
    domain_resolver: DefaultDnsServersIds.RemoteDnsResolver,
    server: '8.8.8.8',
    server_port: '853',
    path: '',
    interface: '',
    inet4_range: '',
    inet6_range: '',
    hosts_path: [],
    predefined: {},
  },
  {
    id: DefaultDnsServersIds.RemoteDnsResolver,
    tag: DefaultDnsServersIds.RemoteDnsResolver,
    detour: DefaultOutboundIds.Select,
    type: DnsServerType.Udp,
    domain_resolver: '',
    server: '8.8.8.8',
    server_port: '53',
    path: '',
    interface: '',
    inet4_range: '',
    inet6_range: '',
    hosts_path: [],
    predefined: {},
  },
]

export const createFakeIPDnsRule = () => ({
  __is_fake_ip: true,
  type: 'logical',
  mode: 'and',
  rules: [
    {
      domain_suffix: [
        '.lan',
        '.localdomain',
        '.example',
        '.invalid',
        '.localhost',
        '.test',
        '.local',
        '.home.arpa',
        '.msftconnecttest.com',
        '.msftncsi.com',
      ],
      invert: true,
    },
    {
      query_type: ['A', 'AAAA'],
    },
  ],
})

export const createDnsRule = (): DnsRuleItem => ({
  id: sampleID(),
  type: DnsRuleType.RuleSet,
  enable: true,
  payload: '',
  action: DnsActionKind.Route,
  invert: false,
  // route
  server: '',
  strategy: '' as DomainStrategy,
  // route/route-options
  disable_cache: false,
  client_subnet: '',
})

export const createDnsRules = (): DnsRuleItem[] => [
  {
    id: sampleID(),
    type: DnsRuleType.ClashMode,
    enable: true,
    payload: ClashMode.Direct,
    action: DnsActionKind.Route,
    server: DefaultDnsServersIds.LocalDns,
    invert: false,
    strategy: '' as DomainStrategy,
    disable_cache: false,
    client_subnet: '',
  },
  {
    id: sampleID(),
    type: DnsRuleType.ClashMode,
    enable: true,
    payload: ClashMode.Global,
    action: DnsActionKind.Route,
    server: DefaultDnsServersIds.RemoteDns,
    invert: false,
    strategy: '' as DomainStrategy,
    disable_cache: false,
    client_subnet: '',
  },
  {
    id: DnsRuleType.InsertionPoint,
    type: DnsRuleType.InsertionPoint,
    enable: true,
    payload: '',
    action: DnsActionKind.Route,
    server: '',
    invert: false,
    strategy: '' as DomainStrategy,
    disable_cache: false,
    client_subnet: '',
  },
  {
    id: sampleID(),
    type: DnsRuleType.RuleSet,
    enable: true,
    payload: DefaultRulesetIds.GEOSITE_CN,
    action: DnsActionKind.Route,
    server: DefaultDnsServersIds.LocalDns,
    invert: false,
    strategy: '' as DomainStrategy,
    disable_cache: false,
    client_subnet: '',
  },
  {
    id: sampleID(),
    type: DnsRuleType.Inline,
    enable: false,
    payload: JSON.stringify(createFakeIPDnsRule(), null, 2),
    action: DnsActionKind.Route,
    server: DefaultDnsServersIds.FakeIP,
    invert: false,
    strategy: '' as DomainStrategy,
    disable_cache: false,
    client_subnet: '',
  },
  {
    id: sampleID(),
    type: DnsRuleType.RuleSet,
    enable: true,
    payload: DefaultRulesetIds.GEOLOCATION_NOT_CN,
    action: DnsActionKind.Route,
    server: DefaultDnsServersIds.RemoteDns,
    invert: false,
    strategy: '' as DomainStrategy,
    disable_cache: false,
    client_subnet: '',
  },
]

export const createDns = (): DnsSection => ({
  servers: createDnsServers(),
  rules: createDnsRules(),
  disable_cache: false,
  disable_expire: false,
  independent_cache: false,
  client_subnet: '',
  final: DefaultDnsServersIds.RemoteDns,
  strategy: '' as DomainStrategy,
})
