import type { DomainStrategy } from '@profile/constant/kernel'
import {
  RouteRuleType,
  RuleSetType,
  RuleSetFormat,
  ClashMode,
  RouteActionKind,
} from '@profile/constant/kernel'
import type { RouteRuleItem, RouteSection, RuleSetItem } from '@profile/types/profiles/route'

import { sampleID } from '@/utils/others'

import {
  DefaultInboundIds,
  DefaultOutboundIds,
  DefaultRulesetIds,
  DefaultDnsServersIds,
} from './shared'

export const createRouteRule = (): RouteRuleItem => ({
  id: sampleID(),
  type: RouteRuleType.RuleSet,
  enable: true,
  payload: '',
  invert: false,
  action: RouteActionKind.Route,
  outbound: '',
  sniffer: [],
  strategy: '' as DomainStrategy,
  server: '',
})

export const createRouteRuleset = (): RuleSetItem => ({
  id: sampleID(),
  type: RuleSetType.Local,
  tag: '',
  format: RuleSetFormat.Binary,
  url: '',
  download_detour: '',
  update_interval: '',
  rules: '',
  path: '',
})

export const createRoute = (): RouteSection => ({
  rules: [
    {
      id: sampleID(),
      type: RouteRuleType.Inbound,
      payload: DefaultInboundIds.Tun,
      enable: true,
      invert: false,
      action: RouteActionKind.Sniff,
      outbound: '',
      sniffer: [],
      strategy: '' as DomainStrategy,
      server: '',
    },
    {
      id: sampleID(),
      type: RouteRuleType.Protocol,
      enable: true,
      payload: 'dns',
      invert: false,
      action: RouteActionKind.HijackDns,
      outbound: '',
      sniffer: [],
      strategy: '' as DomainStrategy,
      server: '',
    },
    {
      id: sampleID(),
      type: RouteRuleType.ClashMode,
      payload: ClashMode.Direct,
      enable: true,
      invert: false,
      action: RouteActionKind.Route,
      outbound: DefaultOutboundIds.Direct,
      sniffer: [],
      strategy: '' as DomainStrategy,
      server: '',
    },
    {
      id: sampleID(),
      type: RouteRuleType.ClashMode,
      enable: true,
      payload: ClashMode.Global,
      invert: false,
      action: RouteActionKind.Route,
      outbound: DefaultOutboundIds.Global,
      sniffer: [],
      strategy: '' as DomainStrategy,
      server: '',
    },
    {
      id: RouteRuleType.InsertionPoint,
      type: RouteRuleType.InsertionPoint,
      enable: true,
      payload: '',
      invert: false,
      action: RouteActionKind.Route,
      outbound: '',
      sniffer: [],
      strategy: '' as DomainStrategy,
      server: '',
    },
    {
      id: sampleID(),
      type: RouteRuleType.Network,
      enable: true,
      payload: 'icmp',
      invert: false,
      action: RouteActionKind.Route,
      outbound: DefaultOutboundIds.Direct,
      sniffer: [],
      strategy: '' as DomainStrategy,
      server: '',
    },
    {
      id: sampleID(),
      type: RouteRuleType.Protocol,
      enable: true,
      payload: 'quic',
      invert: false,
      action: RouteActionKind.Route,
      outbound: DefaultOutboundIds.Block,
      sniffer: [],
      strategy: '' as DomainStrategy,
      server: '',
    },
    {
      id: sampleID(),
      type: RouteRuleType.RuleSet,
      enable: true,
      payload: DefaultRulesetIds.CATEGORY_ADS,
      invert: false,
      action: RouteActionKind.Route,
      outbound: DefaultOutboundIds.Block,
      sniffer: [],
      strategy: '' as DomainStrategy,
      server: '',
    },
    {
      id: sampleID(),
      type: RouteRuleType.RuleSet,
      enable: true,
      payload: DefaultRulesetIds.GEOSITE_PRIVATE,
      invert: false,
      action: RouteActionKind.Route,
      outbound: DefaultOutboundIds.Direct,
      sniffer: [],
      strategy: '' as DomainStrategy,
      server: '',
    },
    {
      id: sampleID(),
      type: RouteRuleType.RuleSet,
      enable: true,
      payload: DefaultRulesetIds.GEOSITE_CN,
      invert: false,
      action: RouteActionKind.Route,
      outbound: DefaultOutboundIds.Direct,
      sniffer: [],
      strategy: '' as DomainStrategy,
      server: '',
    },
    {
      id: sampleID(),
      type: RouteRuleType.RuleSet,
      enable: true,
      payload: DefaultRulesetIds.GEOIP_PRIVATE,
      invert: false,
      action: RouteActionKind.Route,
      outbound: DefaultOutboundIds.Direct,
      sniffer: [],
      strategy: '' as DomainStrategy,
      server: '',
    },
    {
      id: sampleID(),
      type: RouteRuleType.RuleSet,
      enable: true,
      payload: DefaultRulesetIds.GEOIP_CN,
      invert: false,
      action: RouteActionKind.Route,
      outbound: DefaultOutboundIds.Direct,
      sniffer: [],
      strategy: '' as DomainStrategy,
      server: '',
    },
    {
      id: sampleID(),
      type: RouteRuleType.RuleSet,
      enable: true,
      payload: DefaultRulesetIds.GEOLOCATION_NOT_CN,
      invert: false,
      action: RouteActionKind.Route,
      outbound: DefaultOutboundIds.Select,
      sniffer: [],
      strategy: '' as DomainStrategy,
      server: '',
    },
  ],
  rule_set: [
    {
      id: DefaultRulesetIds.CATEGORY_ADS,
      type: RuleSetType.Remote,
      tag: DefaultRulesetIds.CATEGORY_ADS,
      format: RuleSetFormat.Binary,
      url: 'https://testingcf.jsdelivr.net/gh/MetaCubeX/meta-rules-dat@sing/geo/geosite/category-ads-all.srs',
      download_detour: DefaultOutboundIds.Direct,
      update_interval: '',
      rules: '',
      path: '',
    },
    {
      id: DefaultRulesetIds.GEOIP_PRIVATE,
      type: RuleSetType.Remote,
      tag: DefaultRulesetIds.GEOIP_PRIVATE,
      format: RuleSetFormat.Binary,
      url: 'https://testingcf.jsdelivr.net/gh/MetaCubeX/meta-rules-dat@sing/geo/geoip/private.srs',
      download_detour: DefaultOutboundIds.Direct,
      update_interval: '',
      rules: '',
      path: '',
    },
    {
      id: DefaultRulesetIds.GEOSITE_PRIVATE,
      type: RuleSetType.Remote,
      tag: DefaultRulesetIds.GEOSITE_PRIVATE,
      format: RuleSetFormat.Binary,
      url: 'https://testingcf.jsdelivr.net/gh/MetaCubeX/meta-rules-dat@sing/geo/geosite/private.srs',
      download_detour: DefaultOutboundIds.Direct,
      update_interval: '',
      rules: '',
      path: '',
    },
    {
      id: DefaultRulesetIds.GEOIP_CN,
      type: RuleSetType.Remote,
      tag: DefaultRulesetIds.GEOIP_CN,
      format: RuleSetFormat.Binary,
      url: 'https://testingcf.jsdelivr.net/gh/MetaCubeX/meta-rules-dat@sing/geo/geoip/cn.srs',
      download_detour: DefaultOutboundIds.Direct,
      update_interval: '',
      rules: '',
      path: '',
    },
    {
      id: DefaultRulesetIds.GEOSITE_CN,
      type: RuleSetType.Remote,
      tag: DefaultRulesetIds.GEOSITE_CN,
      format: RuleSetFormat.Binary,
      url: 'https://testingcf.jsdelivr.net/gh/MetaCubeX/meta-rules-dat@sing/geo/geosite/cn.srs',
      download_detour: DefaultOutboundIds.Direct,
      update_interval: '',
      rules: '',
      path: '',
    },
    {
      id: DefaultRulesetIds.GEOLOCATION_NOT_CN,
      type: RuleSetType.Remote,
      tag: DefaultRulesetIds.GEOLOCATION_NOT_CN,
      format: RuleSetFormat.Binary,
      url: 'https://testingcf.jsdelivr.net/gh/MetaCubeX/meta-rules-dat@sing/geo/geosite/geolocation-!cn.srs',
      download_detour: DefaultOutboundIds.Direct,
      update_interval: '',
      rules: '',
      path: '',
    },
  ],
  auto_detect_interface: true,
  default_interface: '',
  final: DefaultOutboundIds.Fallback,
  find_process: false,
  default_domain_resolver: {
    server: DefaultDnsServersIds.LocalDns,
    client_subnet: '',
  },
})
